
import { GoogleGenAI, Modality, type GenerateContentResponse } from '@google/genai';
import type { GeminiImagePart, ImageResolution } from '../types';

const handleGeminiError = (error: unknown, context: string): never => {
  console.error(`Error calling ${context}:`, error);
  if (error instanceof Error) {
    const msg = error.message;
    if (msg.includes('RESOURCE_EXHAUSTED') || msg.includes('429')) {
      throw new Error('RATE_LIMIT_EXCEEDED');
    }
    if (msg.includes('PERMISSION_DENIED') || msg.includes('403')) {
      throw new Error('PERMISSION_DENIED');
    }
    throw new Error(`${context} Error: ${msg}`);
  }
  throw new Error(`An unknown error occurred while communicating with the ${context}.`);
};

export const generateImageWithGemini3 = async (
  prompt: string,
  aspectRatio: '1:1' | '16:9' | '9:16' | '4:3' | '3:4',
  resolution: ImageResolution
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: {
        parts: [{ text: prompt }],
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio,
          imageSize: resolution, // 1K, 2K, or 4K
        },
      },
    });

    // Find the image part in the response
    let resultImageUrl = '';
    if (response.candidates && response.candidates[0] && response.candidates[0].content && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                resultImageUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
                break; // Stop after finding the first image
            }
        }
    }

    if (resultImageUrl) {
        return resultImageUrl;
    } else {
        throw new Error('No image was generated by Gemini 3.');
    }

  } catch (error) {
    handleGeminiError(error, "Gemini 3 Image API");
  }
};


export const editImageWithGemini = async (
  images: GeminiImagePart[],
  prompt: string,
  resolution: ImageResolution = '1K', // Add resolution parameter
  aspectRatio: '1:1' | '16:9' | '9:16' | '4:3' | '3:4' = '1:1'
): Promise<GenerateContentResponse> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  try {
    const imageParts = images.map(image => ({
      inlineData: {
        data: image.base64Data,
        mimeType: image.mimeType,
      },
    }));

    const textPart = { text: prompt };
    
    const allParts = [...imageParts, textPart];

    // Use gemini-3-pro-image-preview for high quality editing and resolution control
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview', 
      contents: {
        parts: allParts,
      },
      config: {
        // Gemini 3 Pro Image Preview config for editing
        imageConfig: {
             aspectRatio: aspectRatio,
             imageSize: resolution
        }
      },
    });

    return response;
  } catch (error) {
    handleGeminiError(error, "Gemini API");
  }
};

// Updated function to use Gemini 3 for multimodal prompt refinement
export const refinePrompt = async (
    prompt: string, 
    image: GeminiImagePart | null = null, 
    language: string = 'en'
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  try {
    let systemInstruction = "";
    
    if (image) {
         systemInstruction = "You are an expert prompt engineer for AI image editing. I will provide you with an image and a user request. Your task is to analyze the image's subject, style, and composition, and then write a detailed, descriptive prompt that incorporates the user's request into the scene naturally. The output should be a single paragraph description of the final desired image. Output ONLY the refined prompt text.";
    } else {
         systemInstruction = "You are an expert prompt engineer for AI image generation. Rewrite the following prompt to be more descriptive, detailed, and effective for an AI image generator. Keep the core intent but enhance the artistic style and lighting descriptions. Output ONLY the refined prompt text.";
    }

    if (language === 'zh') {
        systemInstruction += " Please output the result in Traditional Chinese (繁體中文).";
    }

    const contents = [];
    if (image) {
        contents.push({
            inlineData: {
                data: image.base64Data,
                mimeType: image.mimeType
            }
        });
        contents.push({ text: `User Request: ${prompt}\n\nBased on the attached image and the user request, generate a refined prompt.` });
    } else {
        contents.push({ text: `${systemInstruction}\n\nOriginal Prompt: ${prompt}` });
    }

    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-preview', // Supports multimodal input
      contents: {
          role: 'user',
          parts: contents
      },
      config: {
          systemInstruction: image ? systemInstruction : undefined
      }
    });
    return response.text?.trim() || prompt;
  } catch (error) {
    console.error("Error calling Gemini 3 API for refinement:", error);
    return prompt; // Fallback to original prompt on error
  }
};
